// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5uu60Y8LhHiVQecvN7ueQQnJmNfQxNnM',
    appId: '1:958625679906:web:5cec4ceb5b0f8381a1987b',
    messagingSenderId: '958625679906',
    projectId: 'fir-tutorial-ed4ac',
    authDomain: 'fir-tutorial-ed4ac.firebaseapp.com',
    storageBucket: 'fir-tutorial-ed4ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz5x0rWK2SCuFHeb2EPBO4lEGqIbd3lEo',
    appId: '1:958625679906:android:97b362daf4eda37da1987b',
    messagingSenderId: '958625679906',
    projectId: 'fir-tutorial-ed4ac',
    storageBucket: 'fir-tutorial-ed4ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAFup6xcGJm2o7iC4HaYBH4yiBFeYDXQ4',
    appId: '1:958625679906:ios:732013745ef86f9ba1987b',
    messagingSenderId: '958625679906',
    projectId: 'fir-tutorial-ed4ac',
    storageBucket: 'fir-tutorial-ed4ac.appspot.com',
    iosClientId: '958625679906-adf47kg7ujts95s76q9i65v0uqtumnp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAFup6xcGJm2o7iC4HaYBH4yiBFeYDXQ4',
    appId: '1:958625679906:ios:0d4e6988abaca96ba1987b',
    messagingSenderId: '958625679906',
    projectId: 'fir-tutorial-ed4ac',
    storageBucket: 'fir-tutorial-ed4ac.appspot.com',
    iosClientId: '958625679906-61b30p61dur7mstage0jjt96rhlqaprv.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningFirebase.RunnerTests',
  );
}
